DROP TABLE IF EXISTS tgovernor;

CREATE TABLE tgovernor (
  governor_id int GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
  name    VARCHAR(50) NOT NULL,
  age    smallint NOT NULL,
   PRIMARY KEY (governor_id)
) ;
