DROP TABLE IF EXISTS tplanet;

CREATE TABLE tplanet (
  planet_id  int GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) NOT NULL,
  name    VARCHAR(50) NOT NULL,
  governor_id    smallint NOT NULL,
   PRIMARY KEY (planet_id),
   CONSTRAINT FK_tplanet_tgovernor FOREIGN KEY (governor_id)
  REFERENCES tgovernor (governor_id)
) ;
